version: "3.8"
name: demo-stack

networks:
  default:
    name: metriportNetwork
    external: true

services:
  # The node backend service.
  demo-app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      # Ensure the database is loaded before loading the node app
      demo-postgres:
        condition: service_healthy
    environment:
      - DB_CREDS={"password":"admin","dbname":"db","engine":"postgres","port":5432,"host":"demo-postgres","username":"admin"}
      - NODE_ENV=development
      - PORT=8081
    ports:
      - "8081:8081"
      - "9249:9229"
    volumes:
      - ./src:/usr/src/app/src
  # Note that 'postgres' will be the database host name when used in the node app.
  demo-postgres:
    image: postgres:14.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 2s
      timeout: 2s
      retries: 2
